### ISSUE TITLE
[Enhancement] 将运行时保存的数据保存至 `data` 下的子目录

### ISSUE THREAD

**Issue by nullqwertyuiop** [yhluk/Chitung-public#1]
**原因**
七筒运行时生成的 `bankrecord.json` `botconfig.json` `fishrecord.json` `jetpack.txt` `Zeppelin` 文件默认直接储存于 `data` 文件夹下，可能不便用户辨识或与其他插件产生冲突

**改进逻辑**
于 `data` 下新建目录，如 `chitung`，将运行时产生的数据移动至 `data/chitung`，便于辨识

**Comment by KadokawaR** [comment]
已采纳，目前放置在` data/Chitung`  文件夹下。
Implemented in f82e43a6a7fe142d8f0d295360fcdb9cf9f5ddf7.
