### ISSUE TITLE
[Bug Report] 复读时会无视自己发送的消息

### ISSUE THREAD

**Issue by nullqwertyuiop** [yhluk/Chitung-public#3]
**问题**
七筒在复读时会无视自身已发送的消息，用同一内容连续多次触发功能时七筒会对该内容进行复读

**如何复现**
连续多次调用功能，如 `/fish`

**预期行为**
七筒发送消息后重置复读，连续多次调用时不复读触发功能的消息

**使用环境**

系统：Debian Buster x64
Mirai 版本：2.10.1 stable
源码版本：Release v0.1.4

**日志/截图**
![-8e5782a3df0ceb5.jpg](https://user-images.githubusercontent.com/49110142/165010427-b33787aa-9d3f-4a04-83f0-d00b5dcf024d.jpg)

**Comment by KadokawaR** [comment]
Fixed.
Implemented in https://github.com/KadokawaR/Chitung-public/commit/e5568591f53a930e8545d42bbf3da809daa7370e.
